apiVersion: apps/v1
kind: Deployment
metadata:
  name: rulesapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: RulesApi
  template:
    metadata:
      labels:
        app: RulesApi
    spec:
      containers:
      - name: induk
        image: induk.azurecr.io/rules-repo:latest
        ports:
        - containerPort: 8080
          imagePullSecrets:
        - name: induk
       