--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: rulesapi
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: RulesApi
  template: 
    metadata: 
      labels: 
        app: RulesApi
    spec: 
      containers: 
        - 
          image: "induk.azurecr.io/rules-repo:latest"
          name: induk
          ports: 
            - 
              containerPort: 8080
              imagePullSecrets: ~
            - 
              name: induk
--- 
apiVersion: v1
kind: Service
metadata: 
  name: rulesapi
spec: 
  ports: 
    - 
      port: 80
  selector: 
    app: RulesApi
  type: LoadBalancer