--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: rulesapi
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: RulesApi
  template: 
    metadata: 
      labels: 
        app: RulesApi
    spec: 
      containers: 
      - name: induk
        image: "induk.azurecr.io/rules-repo:latest"
        ports: 
        - containerPort: 8080
      imagePullSecrets: 
      - name: induk

--- 
apiVersion: v1
kind: Service
metadata: 
  name: rulesapi
spec: 
  type: LoadBalancer
  ports: 
  - port: 80
  selector: 
    app: RulesApi